.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.38.0 */

nonmatching func_08001F10, 0x10

glabel func_08001F10
    /* 1AD0 08001F10 8C820000 */  lw         $v0, 0x0($a0)
    /* 1AD4 08001F14 8C590000 */  lw         $t9, 0x0($v0)
    /* 1AD8 08001F18 03E00008 */  jr         $ra
    /* 1ADC 08001F1C AC990000 */   sw        $t9, 0x0($a0)
endlabel func_08001F10
